### ISSUE TITLE
request: sound stream complete event or checking for complete stream method 

### ISSUE THREAD

**Issue by gsario** [DigitalStrawberry/ANE-Sounds#13]
It is very important for us to be able to check if sound stream is complete (by id), or get an event on complete (like SOUND_COMPLETE event for SoundChannel in AIR).

Will you be able to add such functional?

**Comment by marpies** [comment]
Unfortunately no, Android implementation uses `SoundPool` class that does not provide any callback for when a sound finishes playing.
