### ISSUE TITLE
Error: Extension context could not be created!

### ISSUE THREAD

**Issue by Shaunmax** [DigitalStrawberry/ANE-Sounds#15]
I am getting the following error, when running the 64 bit android app:- 

```
Error: Extension context could not be created!
	at com.digitalstrawberry.nativeExtensions.anesounds::ANESounds()[/Users/marpies/Work/Freelance/ANE-Sounds/actionscript/src/com/digitalstrawberry/nativeExtensions/anesounds/ANESounds.as:52]
	at com.digitalstrawberry.nativeExtensions.anesounds::ANESounds$/get instance()[/Users/marpies/Work/Freelance/ANE-Sounds/actionscript/src/com/digitalstrawberry/nativeExtensions/anesounds/ANESounds.as:0]
```

@marpies Could you please provide the ane supporting 64 bit! Thanks!

**Comment by Shaunmax** [comment]
Hello Marcel,

Thanks a lot for the quick fix.

But when using the ane on my iOS app i got the following error:
Error #1065: Variable
com.digitalstrawberry.nativeExtensions.anesounds::ANESounds is not defined.

Switching from ane to swc solves the problem, just want to let you know
that ane is not working on iOS!

Thanks & Regards

**Comment by marpies** [comment]
Hi,

Thanks for testing it. I can't reproduce the issue you mentioned however and there are no errors when building and running an iOS project with the ANE included. Are you sure you are linking the ANE correctly in your project? Is it only the latest version of the ANE not working for you?

**Comment by Shaunmax** [comment]
Yes! its the latest version thats giving me error.
Please note that, no error is displayed while building the app only while
using, it throws error.
In my code, I am checking :

if(ANESounds.isSupported())
{
   Flox.logInfo("ANESounds.VERSION - " + ANESounds.VERSION);
}


this is where I am receiving the error message.

**Comment by marpies** [comment]
What AIR version are you using?

**Comment by Shaunmax** [comment]
Air sdk 33.0.2.330

**Comment by marpies** [comment]
Strange, I'm using 33.0.2.338 and it's working fine. Could you try updating your AIR SDK?

According to the error the ANE is not getting packaged in your IPA but it's available in build time. You could also try creating a new project and see if you can get the ANE working there.

**Comment by Shaunmax** [comment]
> Strange, I'm using 33.0.2.338 and it's working fine. Could you try updating your AIR SDK?
> 
> According to the error the ANE is not getting packaged in your IPA but it's available in build time. You could also try creating a new project and see if you can get the ANE working there.

@marpies Thanks for the input! I dint know that we cannot keep both the new & old anes in the same folder, even though we are only using the new one! Deleting the old ane fixed the issue! 

I apologize for the confusion & appreciate your support!

Thank you so much!

**Comment by marpies** [comment]
No worries, glad you sorted it out.
