### ISSUE TITLE
Pause and Resume?

### ISSUE THREAD

**Issue by WinneR2jz** [DigitalStrawberry/ANE-Sounds#16]
Hi! I love this ANE! It helps me so much!
But is it possible to add Pause and Resume methods for any active sound stream? Because after Stop method sound will be play from the beginning.

**Comment by marpies** [comment]
Hi,

We're glad to hear you find the extension useful!

We've added new APIs in the latest release to support pausing and resuming streams.

Let us know if you experience any issues.
