### ISSUE TITLE
stopAllStreams and onSoundChannelCompleted not working on armv7

### ISSUE THREAD

**Issue by Arash-zr** [DigitalStrawberry/ANE-Sounds#18]
it seems like stopAllStreams and onSoundChannelCompleted not working correctly;
I noticed some increasing lags in my game after running some playSound function, then I decided to debug the as3 codes in runtime;
It gets :

```
anesounds/ANESounds.as, Line 240, Column 13	1067: Implicit coercion of a value of type String to an unrelated type int.
anesounds/ANESounds.as, Line 366, Column 12	1067: Implicit coercion of a value of type String to an unrelated type int.
```

somehow "channel" variable detects as String rather than int so I  tried this code and it works. (in runtime);

```
public function stopAllStreams():void
{
	if(_extContext == null)
	{
		for(var streamId:String in _activeStreams)
		{
			stopStream(int(streamId));
		}
	}
	else
	{
		_extContext.call('stopAllStreams');
	}
}
```

```
private function onSoundChannelCompleted(event:Event):void
{
	var channel:SoundChannel = SoundChannel(event.currentTarget);
	for(var streamId:String in _activeStreams)
	{
		if(channel == _activeStreams[streamId])
		{
			deleteStream(int(streamId));
			return;
		}
	}
}
```
although I am not sure what is the exact problem but I can not test this code on my phone either to see if it fixes the problem or not;

I am using 1.10 version

**Comment by marpies** [comment]
Thanks for reporting. We're not sure why that's happening, possibly some issue in AIR when accessing dictionary via for each loop. We've updated the dictionary keys to use `String` instead of `int`.
