### ISSUE TITLE
[Request] Routines to check if sound instance is playing.

### ISSUE THREAD

**Issue by dmunsie** [DigitalStrawberry/ANE-Sounds#20]
ANESounds.instance.isPlaying(soundId:int):Boolean

The above routine would simply return true or false if the passed soundId is currently playing.

A secondary routine would return true of false if any of the min/max soundIds are playing.

ANESounds.instance.isAnyPlaying(min_soundId:int, max_soundId:int):Boolean

So if you passed 3,8 if any of the sounds with ids ranging from 3 to 8 are playing it would return true.

Related question: I noticed the soundid seems to be a linear number that gets incremented when a sound is loaded. Will this number always be incremented even if you are loading/unloading sounds? In my testing this number is always being incremented. I thought maybe if you loaded 10 sounds you would have indexs from 1-10 and then if you unloaded all 10 sounds, the next soundid would start over at 1. Just would like confirmation on behavior. Thx!

**Comment by marpies** [comment]
Unfortunately this is not possible to implement for all platforms as the Android implementation does not have "sound complete" notification, thus we have no way of finding out when the sounds stop playing.

Yes, the sounds id always increments, regardless of sounds being unloaded or not.
