### ISSUE TITLE
Error #1009: Cannot access a property or method of a null object reference.

### ISSUE THREAD

**Issue by dmunsie** [DigitalStrawberry/ANE-Sounds#21]
at com.digitalstrawberry.nativeExtensions.anesounds::ANESounds/playSound()[/Users/marpies/Work/Freelance/ANE-Sounds/actionscript/src/com/digitalstrawberry/nativeExtensions/anesounds/ANESounds.as:175]

One of my apps in development is a shoot-em-up and if it appears if I play too many sounds either at one time or maybe too often, it overloads the audio system somehow and causes the above error. I can replicate it over and over. I can also eliminate the error completely by simply lowering how many sounds are played per second. I use a wrapper to your ane and this is easily controlled. 

Seems like anything faster than launching 20 sounds a second causes the error. Granted this is alot of sounds playing (player firing) and I was originally not even worrying about this due to the docs said when max streams are encountered the oldest one will stop playing. But thx to the error, I recognized my code was allowing way too many sounds to be fired too often (past 30 per second). Technically, through testing it seems like 20 per second or faster causes the error. However I have been testing at max 18 per second with no problems. Thank you.

**Comment by marpies** [comment]
Looks like you're hiting the maximum concurrent sound channel instances supported by AIR. From the [Sound API documentation](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/Sound.html#play()):

> A SoundChannel object, which you use to control the sound. This method returns null if you have no sound card or if you run out of available sound channels. The maximum number of sound channels available at once is 32. 

We've added additional check to prevent accessing `null` channel, the sound will simply not play in this case and the returned sounds id is zero.
