### ISSUE TITLE
Error: Duplicate platform Android-ARM found for extension

### ISSUE THREAD

**Issue by Shaunmax** [DigitalStrawberry/ANE-Sounds#22]
I am getting the following error when trying to compile the project, I just updated the latest ane! 

```
[AIR Debug Launcher]: Error: Duplicate platform Android-ARM found for extension com.digitalstrawberry.nativeExtensions.ANESounds
[AIR Debug Launcher]: The content cannot be loaded because there was a problem loading an extension: Error: Duplicate platform Android-ARM found for extension com.digitalstrawberry.nativeExtensions.ANESounds
java.io.IOException: Stream closed
```

**Comment by ecornbower** [comment]
Sorry for the delay in getting back to you. We're no longer actively updating this repo, but please let us know if you find a solution to your issue in case others have this same problem.

**Comment by Shaunmax** [comment]
> Sorry for the delay in getting back to you. We're no longer actively updating this repo, but please let us know if you find a solution to your issue in case others have this same problem.

I just reverted back to previous version!

**Comment by ecornbower** [comment]
Glad that worked!
