### ISSUE TITLE
How to use this ANE in the Flashdevelop?

### ISSUE THREAD

**Issue by Arash-zr** [DigitalStrawberry/ANE-Sounds#3]
I need a Flashdevelop template , it doesn't work when i try to use it in the Flashdevelop.

**Comment by ecornbower** [comment]
We don't have any plans on adding a Flash Develop template. It sounds like the sound files are not being embedded correctly in your app. Are you receiving any errors when debugging?

You can also download a free trial of IntelliJ and see if you can get it to work there first.

**Comment by Arash-zr** [comment]
There's no errors with the compiling .I think my sound is embedded in my app

Edit: 
I solve it : There's some java file so flashdevelop can't recognize it !
However thanks.
