### ISSUE TITLE
Unloading sounds

### ISSUE THREAD

**Issue by SlavomirDurej** [DigitalStrawberry/ANE-Sounds#4]
First of all , thanks for this awesome ANE, great work mate!

Just wondering.. would it be possible to get unloading sounds from memory functionality as well?
Just do we can do a nice memory clean up, for the sounds we no longer need. 

This would be especially useful in music apps type,  where you want to load a new set of sounds (or samples) for a new keyboard instrument.

**Comment by ecornbower** [comment]
Thanks for the compliments! This should be possible; I'll have one of our devs look into it further and see how much work it would take to implement.

**Comment by SlavomirDurej** [comment]
excellent, thank you very much. Please let me know what I can do to help as well!

**Comment by marpies** [comment]
We've added the `unloadSound` method. Its usage is rather straightforward, as you can see on the readme page. Let us know if you find any issues.

**Comment by SlavomirDurej** [comment]
Perfect, thank you so much, will test this and let you know if I found any issues.
