### ISSUE TITLE
Adding some other useful methodsto the api

### ISSUE THREAD

**Issue by SlavomirDurej** [DigitalStrawberry/ANE-Sounds#5]
Hi guys

very happy with your ANE, thanks for making it available!

I was hoping you would consider perhaps adding a couple more methods to the api ?

1) Stopping playing sound

e.g : ANESounds.instance.stopSound(soundID)
this would stop currently playing sound, which would be useful with longer sounds or sounds playing in the loop. 
(Alternatively you could implement stopping the sound when calling unload() if that's easier ? )

2) access to volume of a playing sound so it can faded in  / faded out 

e.g. ANESounds.instance.setVolume(soundID,volumeLeft,volumeRight);
or just 
ANESounds.instance.setVolume(soundID,volume); //set to both channels if that's easier

volume would be a number from 0-1 obviously.

Many thanks!

Slav

**Comment by ecornbower** [comment]
Thanks for the suggestions, those do seem like two worthwhile additions that could be made. I'll have one of our developers look into this more and see how feasible it would be.

**Comment by marpies** [comment]
We've added the methods you suggested. Note that playing long sounds like background music is not recommended as the Android implementation uses low latency playback mode which is more suited for short sound effects, e.g. button clicks.

**Comment by SlavomirDurej** [comment]
excellent, thank you guys! 
Yes, will use this for shorter sounds only, but helps to have it there, especially the volume adjustment!
cheers, again!
