### ISSUE TITLE
Continuously loading takes extra time.

### ISSUE THREAD

**Issue by omakeya** [DigitalStrawberry/ANE-Sounds#7]
When I load a few sounds,  there is no problem. 

example:
ANESounds.instance.loadSound(A)     10ms

ANESounds.instance.loadSound(A)
ANESounds.instance.loadSound(A)      20ms

ANESounds.instance.loadSound(A)     
ANESounds.instance.loadSound(A)     
ANESounds.instance.loadSound(A)     30ms

But  loding 5 or more sounds continuously makes unusual behaior

example:
ANESounds.instance.loadSound(A)*5       400ms

ANESounds.instance.loadSound(A)*6       500ms

ANESounds.instance.loadSound(A)*10       1000ms

How to solve this problem or I did something wrong?

**Comment by ecornbower** [comment]
Thanks for letting us know about this issue. @marpies any ideas what is going on with this?

**Comment by marpies** [comment]
It looks like SoundPool on Android does not handle too many load requests very well. Apparently there's not much to be done about that except for loading the sounds in smaller batches and not all at once.

I've updated the Android library with a queued loading so the app will no longer freeze for several seconds when calling the `loadSound` method multiple times at once. Note the sound may not be available to be played immediately after you call the load method, but you can add an event listener to find out when a sound is loaded:

```as3
ANESounds.instance.addEventListener(SoundEvent.LOAD, onSoundLoaded);
var soundId:int = ANESounds.instance.loadSound(...);

private function onSoundLoaded(event:SoundEvent):void
{
    trace("Sound", event.soundId, "loaded");
}
```

**Comment by omakeya** [comment]
Thank you for quick update!
