### ISSUE TITLE
stopStream not working

### ISSUE THREAD

**Issue by iLKke** [DigitalStrawberry/ANE-Sounds#8]
Supposedly stopSound has been changed to stopStream from version 1.4 but opening the ANE reveals it still contains stopSound in it. 

As a result I am getting compile errors if I use stopSound and on-device runtime errors if I use stopStream.

This is the same in 1.4 and 1.5

**Comment by marpies** [comment]
This sounds like you have conflicts in your project and could be referencing different versions of the ANE. If you are using an IDE to do the compiling/packaging then it is possible you have several Sounds ANEs in some temporary directory which the IDE uses to store all the ANEs used in your project.

**Comment by iLKke** [comment]
Thanks for the idea. I removed the swc and tracked down and cleared all the other temporary copies, but the problem persists.

Here's is the error I get when I debug remotely on device:

```
ArgumentError: Error #3500: The extension context does not have a method with the name stopStream.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.digitalstrawberry.nativeExtensions.anesounds::ANESounds/stopStream()[/Users/marpies/Work/Freelance/ANE-Sounds/actionscript/src/com/digitalstrawberry/nativeExtensions/anesounds/ANESounds.as:225]
```
Line 225 of ANESounds.as is
```_extContext.call('stopStream', streamId);```

**Comment by marpies** [comment]
Indeed, there was a problem with the `stopStream` method on Android. Thanks for reporting.

Please update to `v1.6` where the issue is fixed.

**Comment by iLKke** [comment]
Cheers for the quick fix

**Comment by iLKke** [comment]
Would it be too much to ask for a stopAllStreams() sometime in the future?

**Comment by marpies** [comment]
Sure, create a new issue request and we'll see what we can do.
