### ISSUE TITLE
request: A way to stop all streams at once

### ISSUE THREAD

**Issue by iLKke** [DigitalStrawberry/ANE-Sounds#9]
Something like stopAllStreams() to kill all sounds without having to keep track of all the IDs.

**Comment by dmunsie** [comment]
Related request: Stop(soundID) which would then stop all streams that reference that soundID.

**Comment by marpies** [comment]
Thanks for the feedback. We've added two new methods in the [v1.8 release](https://github.com/DigitalStrawberry/ANE-Sounds/releases/tag/v1.8):

```as3
ANESounds.instance.stopAllStreams();
ANESounds.instance.stopStreamsForSound(soundId);
```
